version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: .
    command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/open_api_training
      - bundle-install:/usr/local/bundle:delegated
      - rails-tmp:/open_api_training/tmp
    ports:
      - "3001:3000"
    links:
      - db

volumes:
  db-data:
  rails-tmp:
  bundle-install:
